import LocalizedStrings from 'react-native-localization';

const strings = new LocalizedStrings({
  en: {
    login: 'Log in',
    close: 'Close',
    cancel: 'Cancel',
    away: 'away',
    join: 'JOIN',
    ago: 'ago',
    tapToLook: 'Tap to look',
    messages: 'Messages',
    newMessage: '+ New',
    me: 'Me',
    myProfile: 'My profile',
    myParty: 'My party',
    myNotifications: 'Notifications',
    myAttendings: 'My attendings',
    myShoutouts: 'My shoutouts',
    myAchievements: 'My achievements',
    noGuests: 'No guests',
    guests: 'Guests',
    distance: 'Distance',
    time: 'Time',
    date: 'Date',
    houserules: 'Houserules',
    achievements: 'Achievements',
    showMap: 'SHOW MAP',
    showParty: 'SHOW PARTY',
    accept: 'ACCEPT',
    decline: 'DECLINE',
    editParty: 'Edit party',
    newShoutout: 'New shoutout',
    newParty: 'New party',
    shoutoutPlaceholder: 'Create a new shoutout to everyone in',
    onGoingParties: 'Ongoing parties',
    pastParties: 'Past parties',
    upcomingParties: 'Upcoming parties',
    choosePartyPic: 'Choose a party picture!',
    otherPic: 'Choose another picture',
    save: 'SAVE',
    publish: 'PUBLISH',
    title: 'Title',
    titleForParty: 'Title for the party',
    gender: 'Gender',
    age: 'Age',
    girls: 'Girls',
    boys: 'Boys',
    both: 'Both',
    place: 'Location',
    useCurrentLocation: 'Use current location',
    hideParty: 'Hide party',
    availability: 'Availability',
    more: 'More',
    invite: 'Invite',
    invited: 'Invited',
    showShoutout: 'SHOW S/O',
    addACaption: 'Add a caption!',
    attending: 'ATTENDING',
    notAttending: 'LEAVE PARTY',
    editProfile: 'Edit Profile',
    done: 'Done',
    changeProfilePic: 'Change Profile Photo',
    saveSmall: 'Save',
    chooseBirthdate: 'Set your birthdate',
    inviteFriends: 'Invite friends',
    continue: 'CONTINUE',
    acceptInvite: 'Accept Invite',
    inviteCaps: 'INVITED',
    deleteParty: 'Delete party',
    takePhotoButtonTitle: 'Take photo...',
    chooseFromLibraryButtonTitle: 'Choose from library...',
    choosePhoto: 'Pick a pic',
    noBio: 'This user has no bio...',
    to: 'to',
    lookingFor: 'Looking for',
    EDIT: 'EDIT',
    chat: 'Chat',
    inviteSent: 'Invite sent',
    invCaps: 'INVITE',
    address: 'Address',
    wantToPartyWith: 'I want to party with',
    usePicture: 'USE PICTURE',
    legal: 'Legal',
    points: 'points',
    search: 'Search',
    createParty: 'New party',
    createShoutout: 'New shoutout',
    showHits: 'Apply filter',
    lookingForBoth: 'both genders',



    //No shit nearby strings
    noPartiesNearby: 'There are no parties nearby. Be the first to create one!',
    noShoutoutsNearby: 'There are no shoutouts nearby, Be the first to scream!',
    noAttendings: 'You are not attending any parties',
    noFilterMatch: 'No parties matched your filter',
    noOngoingParties: 'No ongoing parties',
    noPastParties: 'No past parties',



    // Calender stuff
    sun: 'SUN',
    mon: 'MON',
    tue: 'TUE',
    wed: 'WED',
    thu: 'THU',
    fri: 'FRI',
    sat: 'SAT',
    jan: 'JANUARY',
    feb: 'FEBRUARY',
    mar: 'MARCH',
    apr: 'APRIL',
    may: 'MAY',
    jun: 'JUNE',
    jul: 'JULY',
    aug: 'AUGUST',
    sep: 'SEPTEMBER',
    oct: 'OCTOBER',
    nov: 'NOVEMBER',
    dec: 'DECEMBER',
    years: 'years',
    pending: 'PENDING',

    //Notification-strings
    joinAccepted: 'You are welcome to join',
    joinParty: 'wants to join',

    //Error strings
    missingTitle: 'The party needs a title',
    missingHouserules: 'The party needs some rules',
    missingGender: 'What gender do you want to party with?',
    missingPicture: 'The party needs a picture!',
    missingAddress: 'The party needs an address',
    distanceVeryClose: 'Very close',
    distanceClose: 'Close',
    noInternetConnection: 'Something went wrong. Check your connection',
    noChats: 'You have no chats currently'
  },
  'nb-NO': {
    login: 'Logg inn',
    close: 'Lukk',
    cancel: 'Avbryt',
    away: 'unna',
    join: 'BLI MED',
    ago: 'siden',
    tapToLook: 'Tap for å se',
    messages: 'Meldinger',
    newMessage: '+ Ny',
    me: 'Meg',
    myProfile: 'Min profil',
    myParty: 'Min fest',
    myNotifications: 'Varsler',
    myAttendings: 'Mine deltagelser',
    myShoutouts: 'Mine shoutouts',
    myAchievements: 'Mine premier',
    noGuests: 'Ingen gjester',
    guests: 'Gjester',
    distance: 'Avstand',
    time: 'Tid',
    date: 'Dato',
    houserules: 'Husregler',
    achievements: 'Premier',
    showMap: 'VIS KART',
    showParty: 'VIS FEST',
    accept: 'GODTA',
    decline: 'AVSLÅ',
    editParty: 'Rediger fest',
    newShoutout: 'Ny shoutout',
    newParty: 'Ny fest',
    shoutoutPlaceholder: 'Lag en ny shoutout til alle i',
    onGoingParties: 'Pågående fester',
    pastParties: 'Tidligere fester',
    upcomingParties: 'Kommende fester',
    choosePartyPic: 'Velg et festbilde!',
    otherPic: 'Velg et annet bilde',
    save: 'LAGRE',
    publish: 'PUBLISER',
    title: 'Tittel',
    titleForParty: 'Tittel på festen',
    gender: 'Kjønn',
    age: 'Alder',
    girls: 'Jenter',
    boys: 'Gutter',
    both: 'Begge',
    place: 'Plass',
    useCurrentLocation: 'Bruk nåværende plassering',
    hideParty: 'Skjul festen',
    availability: 'Tilgjengelighet',
    more: 'Mer',
    invite: 'Inviter',
    invited: 'Inviterte',
    pending: 'AVVENTER',
    showShoutout: 'VIS S/O',
    addACaption: 'Legg til en caption',
    attending: 'SKAL',
    notAttending: 'Forlat festen',
    editProfile: 'Rediger Profil',
    done: 'Ferdig',
    changeProfilePic: 'Endre profilbilde',
    saveSmall: 'Lagre',
    chooseBirthdate: 'Sett fødselsdato',
    inviteFriends: 'Inviter venner',
    continue: 'FORTSETT',
    acceptInvite: 'Godta invitasjon',
    inviteCaps: 'INVITERT',
    deleteParty: 'Slett fest',
    takePhotoButtonTitle: 'Ta bilde...',
    chooseFromLibraryButtonTitle: 'Velg fra biblioteket...',
    choosePhoto: 'Velg bilde',
    noBio: 'Denne brukeren har ingen bio...',
    to: 'til',
    lookingFor: 'Ser etter',
    EDIT: 'REDIGER',
    inviteSent: 'Invitasjon sendt',
    invCaps: 'INVITER',
    address: 'Adresse',
    wantToPartyWith: 'Jeg vil feste med',
    usePicture: 'BRUK BILDE',
    legal: 'Juridisk',
    points: 'poeng',
    search: 'Søk',
    createParty: 'Ny fest',
    createShoutout: 'Ny shoutout',
    showHits: 'Vis treff',
    lookingForBoth: 'begge kjønn',

    //No shit nearby strings
    noPartiesNearby: 'Det er ingen fester i nærheten. Bli den første!',
    noShoutoutsNearby: 'Det er ingen shoutouts i nærheten. Bli den første!',
    noAttendings: 'Du er ikke med på noen fester',
    noFilterMatch: 'Fant ingen fester med dette filteret',
    noOngoingParties: 'Ingen pågående fester',
    noPastParties: 'Ingen tidligere fester',


    //Calendar strings
    sun: 'SØN',
    mon: 'MAN',
    tue: 'TIR',
    wed: 'ONS',
    thu: 'TOR',
    fri: 'FRE',
    sat: 'LØR',
    jan: 'JANUAR',
    feb: 'FEBRUAR',
    mar: 'MARS',
    apr: 'APRIL',
    may: 'MAI',
    jun: 'JUNI',
    jul: 'JULI',
    aug: 'AUGUST',
    sep: 'SEPTEMBER',
    oct: 'OKTOBER',
    nov: 'NOVEMBER',
    dec: 'DESEMBER',
    years: 'år',

    //Notification-strings
    joinAccepted: 'Du er velkommen på',
    joinParty: 'ønsker å bli med på',

    //Error strings
    missingTitle: 'Festen trenger en tittel',
    missingHouserules: 'Festen trenger noen regler',
    missingGender: 'Hvilket kjønn vil du feste med?',
    missingPicture: 'Festen trenger et bilde',
    missingAddress: 'Festen trenger en adresse',
    distanceVeryClose: 'Veldig nær',
    distanceClose: 'Nær',
    noInternetConnection: 'Noe gikk galt. Sjekk tilkoblingen',
    noChats: 'Du har ingen pågående chats'

  }
});

module.exports = strings;
